version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 1234
      TZ: 'Europe/Madrid'
    networks:
      - wordpress-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  wordpress:
    depends_on:
      db:
        condition: service_healthy
    image: wordpress:latest
    user: "1000:1000"  # Usa tu ID de usuario local
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      TZ: 'Europe/Madrid'
      WORDPRESS_CONFIG_EXTRA: |
        /* Configuración de idioma */
        define('WPLANG', 'es_ES');
        define('WP_LANG_DIR', ABSPATH . 'wp-content/languages');
        /* Deshabilitar solicitudes de credenciales FTP */
        define('FS_METHOD', 'direct');
        define('FS_CHMOD_DIR', 0775);
        define('FS_CHMOD_FILE', 0664);
        /* Configuración adicional */
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
    networks:
      - wordpress-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
      UPLOAD_LIMIT: 100M
      MEMORY_LIMIT: 256M
      PMA_ABSOLUTE_URI: http://localhost:8080/
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge

volumes:
  db_data:
    driver: local
